import { z } from "zod";

export const resourceItemSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1, "Resource title is required"),
  type: z.enum(["FILE", "LINK", "NOTE", "CODE_SNIPPET"]),
  url: z.string().url("Invalid resource URL").optional().nullable(),
  publicId: z.string().optional().nullable(),
  fileSize: z.number().int().optional().nullable(),
  fileType: z.string().optional().nullable(),
  content: z.string().optional().nullable(),
});

const cohortSessionBaseSchema = z.object({
  // sessionNumber & dayNumber are auto-generated by the service if omitted
  sessionNumber: z.number().int().positive().optional(),
  dayNumber: z.number().int().positive().optional(),
  title: z.string().min(3, "Title must be at least 3 characters").max(100).optional(),
  scheduledAt: z.string().datetime("Scheduled time must be a valid ISO 8601 date string").optional(),
  durationMinutes: z.number().int().positive().optional().default(60),
  // accept both creditCost and creditPrice (Postman uses creditPrice)
  creditCost: z.number().int().nonnegative().optional(),
  creditPrice: z.number().int().nonnegative().optional(),
  joinLink: z.string().url("Invalid join link URL").optional().nullable(),
  resources: z.array(resourceItemSchema).optional(),
});

const normalizeCreditCost = (data: z.infer<typeof cohortSessionBaseSchema>) => ({
  ...data,
  creditCost: data.creditCost ?? data.creditPrice ?? 0,
});

export const createCohortSessionSchema = cohortSessionBaseSchema
  .required({ title: true, scheduledAt: true })
  .transform(normalizeCreditCost);

export const updateCohortSessionSchema = cohortSessionBaseSchema.transform(normalizeCreditCost);

export const addSessionResourceSchema = resourceItemSchema;

